export const products = [
  {
    id: "ultra-instinct",
    slug: "ultra-instinct",
    name: "Ultra Instinct",
    priceSek: 289,
    stockQuantity: 14,
    note: "Peach ice tea / clean focus",
    description: "Kyld peach ice tea-vibe med clean energi och en front som ser byggd ut for ren fokus.",
    badge: "Focus",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #10214f, #12476a 55%, #5ce1ff)",
    image: "bilder/UltraInstinct/T/UltraInstinctV2_Front-removebg-preview.png",
    flavorBadge: "Clean / Focus",
    flavorTag: "Peach Ice Tea",
    flavorNotes: "<strong>Vibe:</strong> peach ice tea med clean kyla, neonprecision och high-performance kansla utan brus.",
    profile: "Locked-in mode",
    bestFor: "Scrims och fokusblock",
    packSub: "Peach ice tea. Clean hit. Focus mode."
  },
  {
    id: "loot-devil-fruit-dose",
    slug: "loot-devil-fruit-dose",
    name: "Devil Fruit",
    priceSek: 289,
    stockQuantity: 11,
    note: "Multivitamin / anime drop",
    description: "Fruktig multivitamin-profil med stark shonen-vibe och ett uttryck som kanns collector-grade.",
    badge: "Anime",
    tagTone: "",
    swatch: "linear-gradient(135deg, #57207f, #b6276d 52%, #ff9a57)",
    image: "bilder/loot-devil-fruit-dose/T/02-loot-devil-fruits-gaming-booster-frontal_jpg-removebg-preview.png",
    flavorBadge: "Fruit / Bright",
    flavorTag: "Multivitamin",
    flavorNotes: "<strong>Vibe:</strong> tropisk multivitamin med anime-energi, samlarbar front och tydlig power-up kansla.",
    profile: "Shonen power-up",
    bestFor: "Senkvallar och stream hype",
    packSub: "Multivitamin. Bright hit. Anime energy."
  },
  {
    id: "limited-black-loot-edition",
    slug: "limited-black-loot-edition",
    name: "Black LOOT Edition",
    priceSek: 289,
    stockQuantity: 0,
    note: "Blackberry / blackcurrant dark",
    description: "Mork berry-profil i black edition-form med samma premiumdrop-kansla som en limiterad release.",
    badge: "Limited",
    tagTone: "",
    swatch: "linear-gradient(135deg, #10131b, #2c173d 52%, #7f2f5d)",
    image: "bilder/limited-black-loot-edition/T/02-black-loot-clover-curse-gamer-energy-frontal_jpg-removebg-preview.png",
    flavorBadge: "Sour / Dark",
    flavorTag: "Black Edition",
    flavorNotes: "<strong>Vibe:</strong> sour blackberry och blackcurrant i svart limited look som kanns dyrare direkt.",
    profile: "Rare loot drop",
    bestFor: "Nattpass och ranked grind",
    packSub: "Blackberry. Blackcurrant. Dark neon."
  },
  {
    id: "rare-raspberry",
    slug: "rare-raspberry",
    name: "Rare Raspberry",
    priceSek: 289,
    stockQuantity: 9,
    note: "Raspberry / sweet-sour",
    description: "Hallonprofil med candy edge och en visuell ton som skriker streamer energy utan att bli barnslig.",
    badge: "Top Pick",
    tagTone: "",
    swatch: "linear-gradient(135deg, #40164a, #92254b 50%, #ff7c96)",
    image: "bilder/rare-raspberry/T/02-loot-rare-rasperry-gamer-energy-frontal_jpg-removebg-preview.png",
    flavorBadge: "Berry / Candy",
    flavorTag: "Raspberry",
    flavorNotes: "<strong>Vibe:</strong> sweet-sour raspberry med candy-glow och en tydlig rare drop-kansla i kortet.",
    profile: "Streamer candy",
    bestFor: "Late night queue sessions",
    packSub: "Raspberry. Sweet-sour. Candy glow."
  },
  {
    id: "cactus-calamity",
    slug: "cactus-calamity",
    name: "Cactus Calamity",
    priceSek: 289,
    stockQuantity: 7,
    note: "Cactus lime / sharp fresh",
    description: "Skarp, frisk profil med okenvibe och ett uttryck som sticker ut direkt i produktgrid och showcase.",
    badge: "Wildcard",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #0f342b, #256f4b 56%, #c8ff63)",
    image: "bilder/cactus-calamity/T/02-CactusCalamity_Front-removebg-preview.png",
    flavorBadge: "Fresh / Sharp",
    flavorTag: "Cactus Lime",
    flavorNotes: "<strong>Vibe:</strong> cactus lime med frisk punch, torr heat och en look som kanns som desert-tech.",
    profile: "Sharp refresh",
    bestFor: "Dagpass och comeback games",
    packSub: "Cactus lime. Sharp fresh. Desert tech."
  },
  {
    id: "loot-sour-shock-dose",
    slug: "loot-sour-shock-dose",
    name: "Sour Shock",
    priceSek: 289,
    stockQuantity: 0,
    note: "Sour candy / electric hit",
    description: "En mer aggressiv sour-profil med elektrisk look och tydligt gamer-plock for folk som vill ha edge.",
    badge: "Shock",
    tagTone: "",
    swatch: "linear-gradient(135deg, #19244f, #2f3ed9 45%, #63f0ff)",
    image: "bilder/loot-sour-shock-dose/T/02-loot-sour-shock-gamer-energy-frontal_jpg-removebg-preview.png",
    flavorBadge: "Sour / Electric",
    flavorTag: "Shock Candy",
    flavorNotes: "<strong>Vibe:</strong> sour candy med elblatt glow, snabb attack och en hardcore arena-kansla.",
    profile: "Electric rush",
    bestFor: "Clutch games och hard reset",
    packSub: "Sour candy. Electric hit. Fast reset."
  },
  {
    id: "loot-tiki-tropicali-dose",
    slug: "loot-tiki-tropicali-dose",
    name: "Tiki Tropicali",
    priceSek: 289,
    stockQuantity: 12,
    note: "Tropical mix / beach energy",
    description: "Tropisk profil med varma farger och semesterhype, men fortfarande stylad som en premium cube-drop.",
    badge: "Tropical",
    tagTone: "",
    swatch: "linear-gradient(135deg, #4f1d3c, #d55b3a 52%, #ffcf63)",
    image: "bilder/loot-tiki-tropicali-dose/T/02-loot-tiki-tropicali-gaming-booster-frontal_jpg-removebg-preview.png",
    flavorBadge: "Tropical / Warm",
    flavorTag: "Island Mix",
    flavorNotes: "<strong>Vibe:</strong> tropisk mix med varm glow, candy-fruit ton och semesterdrop fast i gamer-form.",
    profile: "Vacation stack",
    bestFor: "Lan, content nights",
    packSub: "Tropical mix. Warm glow. Island energy."
  },
  {
    id: "loot-kimetsu-no-kiba-dose",
    slug: "loot-kimetsu-no-kiba-dose",
    name: "Kimetsu No Kiba",
    priceSek: 289,
    stockQuantity: 0,
    note: "Limited anime / collector front",
    description: "Anime collab-look med tung limited-kansla och en diagonal packshot som ser byggd for hype ut.",
    badge: "Collab",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #123252, #1e5c4f 48%, #9ad56a)",
    image: "bilder/loot-kimetsu-no-kiba-dose/T/03-LOOT-KimetsunoKiba-Diagonal-removebg-preview.png",
    flavorBadge: "Anime / Limited",
    flavorTag: "Collector",
    flavorNotes: "<strong>Vibe:</strong> limited anime drop med collector-front, manga-energi och collab-tyngd i varje view.",
    profile: "Collector flex",
    bestFor: "Display shelf och fan drops",
    packSub: "Anime collab. Limited flex. Collector glow."
  },
  {
    id: "loot-phoenix-flames-dose",
    slug: "loot-phoenix-flames-dose",
    name: "Phoenix Flames",
    priceSek: 289,
    stockQuantity: 6,
    note: "Fiery fruit / red-orange heat",
    description: "Eldig profil med phoenix-farger och stark diagonal silhuett som gor smaken till ett naturligt center card.",
    badge: "Hot Drop",
    tagTone: "",
    swatch: "linear-gradient(135deg, #48182f, #c2362f 48%, #ffb35d)",
    image: "bilder/loot-phoenix-flames-dose/T/02-LOOT-PhoenixFlames-diagonal-removebg-preview.png",
    flavorBadge: "Fiery / Loud",
    flavorTag: "Phoenix",
    flavorNotes: "<strong>Vibe:</strong> fiery fruit med varm glow, loud contrast och full phoenix-revival energi.",
    profile: "Hot streak",
    bestFor: "Win streaks och montage nights",
    packSub: "Fiery fruit. Loud glow. Revival mode."
  },
  {
    id: "invincible-ice-tea",
    slug: "invincible-ice-tea",
    name: "Invincible Ice Tea",
    priceSek: 289,
    stockQuantity: 8,
    note: "Ice tea / smooth chill",
    description: "En smooth ice tea-variant med sval premiumkansla och mjukare profil for kunder som vill ha clean refresh.",
    badge: "Smooth",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #25314c, #62748c 50%, #d7efff)",
    image: "bilder/invincible-ice-tea/T/03-PixelPeachIceTea_Front-removebg-preview.png",
    flavorBadge: "Iced / Smooth",
    flavorTag: "Ice Tea",
    flavorNotes: "<strong>Vibe:</strong> sval ice tea med smooth finish, clean premiumton och mindre aggressiv energikansla.",
    profile: "Chill focus",
    bestFor: "Long sessions utan overload",
    packSub: "Ice tea. Smooth chill. Clean refresh."
  }
];

export const productMap = new Map(products.map((product) => [product.id, product]));

export function formatSek(amount) {
  return `${amount} SEK`;
}
