export const products = [
  {
    id: "ultra-instinct",
    slug: "ultra-instinct",
    name: "Ultra Instinct",
    priceSek: 289,
    stockQuantity: 14,
    note: "Chicha morada / varm och fruktig",
    description: "Chicha morada har en unik och uppfriskande smak som kan beskrivas som söt, fruktig och aromatisk – tänk dig en blandning mellan en kryddig fruktpunch och en len druvjuice.",
    badge: "Focus",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #10214f, #12476a 55%, #5ce1ff)",
    image: "bilder/UltraInstinct/T/UltraInstinctV2_Front-removebg-preview.png",
    imageV1: "bilder/UltraInstinct/T/UltraInstinctV2_Front-removebg-preview.png",
    imageV2: "bilder/UltraInstinct/T/Side/UltraInstinctV2_Front.Side.Right-removebg-preview.png",
    flavorBadge: "Julig / Fruktbål",
    flavorTag: "Chicha morada",
    flavorNotes: "<strong>Vibe:</strong> Chicha morada, Kryddig druvjuice.",
    profile: "Den tänkande spelaren",
    bestFor: "Sena kvällar med RTS",
    packSub: "Kryddig druvjuice"
  },
  {
    id: "loot-devil-fruit-dose",
    slug: "loot-devil-fruit-dose",
    name: "Devil Fruit",
    priceSek: 289,
    stockQuantity: 11,
    note: "Multivitamin | anime drop",
    description: "Fruktig multivitamin-smak med tydlig “juicecocktail”-känsla. Frisk och lätt att dricka ofta, en sån där klassisk smakupplvelser av guldiga 'klock' toner",
    badge: "Anime",
    tagTone: "",
    swatch: "linear-gradient(135deg, #57207f, #b6276d 52%, #ff9a57)",
    image: "bilder/loot-devil-fruit-dose/T/02-loot-devil-fruits-gaming-booster-frontal_jpg-removebg-preview.png",
    imageV1: "bilder/loot-devil-fruit-dose/T/02-loot-devil-fruits-gaming-booster-frontal_jpg-removebg-preview.png",
    imageV2: "bilder/loot-devil-fruit-dose/T/Side/06-loot-devil-fruits-gaming-booster-profil_jpg-removebg-preview.png",
    flavorBadge: "Fruit / Bright",
    flavorTag: "Multivitamin",
    flavorNotes: "<strong>Vibe:</strong> tropisk multivitamin med anime-energi, samlarbar front och tydlig power-up kansla.",
    profile: "Meme-samlaren",
    bestFor: "Twitch på en skärmen, spel på andra",
    packSub: "Fruktig Multivitamin"
  },
  {
    id: "limited-black-loot-edition",
    slug: "limited-black-loot-edition",
    name: "Black Clover Curse",
    priceSek: 289,
    stockQuantity: 0,
    note: "Björnbär | Svarta vinbär",
    description: "Mörka-bär med tydlig syra. En Sagolik smak av björnbär och svartvinbär med skarp svart karaktär som ger tillbakablick utav skolutflykten bland berg och skog.",
    badge: "Limited",
    tagTone: "",
    swatch: "linear-gradient(135deg, #10131b, #2c173d 52%, #7f2f5d)",
    image: "bilder/limited-black-loot-edition/T/02-black-loot-clover-curse-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV1: "bilder/limited-black-loot-edition/T/02-black-loot-clover-curse-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV2: "bilder/limited-black-loot-edition/T/Side/06-black-loot-clover-curse-gamer-energy-profil_jpg-removebg-preview.png",
    flavorBadge: "Sour / Dark",
    flavorTag: "Black Edition",
    flavorNotes: "<strong>Vibe:</strong> sour blackberry och blackcurrant i svart limited look som kanns dyrare direkt.",
    profile: "Inget före 2008, tack",
    bestFor: "Soliga dagar, persiennerna nere",
    packSub: "Björnbär & Svarta vinbär"
  },
  {
    id: "rare-raspberry",
    slug: "rare-raspberry",
    name: "Rare Raspberry",
    priceSek: 289,
    stockQuantity: 9,
    note: "Raspberry / sweet-sour",
    description: "Blå-hallon-profil. En fyllig fruktig smak av hallon med en unik karaktär som ger en tydlig friskhet som motverkar att den blir för sliskig.",
    badge: "Top Pick",
    tagTone: "",
    swatch: "linear-gradient(135deg, #40164a, #92254b 50%, #ff7c96)",
    image: "bilder/rare-raspberry/T/02-loot-rare-rasperry-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV1: "bilder/rare-raspberry/T/02-loot-rare-rasperry-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV2: "bilder/rare-raspberry/T/Side/05-loot-rare-raspberry-gamer-booster-mit-shake.png",
    flavorBadge: "Berry / Candy",
    flavorTag: "Raspberry",
    flavorNotes: "<strong>Vibe:</strong> sweet-sour raspberry med candy-glow och en tydlig rare drop-kansla i kortet.",
    profile: "Spelar bara ranked",
    bestFor: "Snabba köer och långa nätter",
    packSub: "Sötsur godis hallon"
  },
  {
    id: "cactus-calamity",
    slug: "cactus-calamity",
    name: "Cactus Calamity",
    priceSek: 289,
    stockQuantity: 7,
    note: "Cactus lime / sharp fresh",
    description: "Exotisk lemonad av kaktusfikon & calamansi, en framträdande ton av citrus som ger en frisk och syrlig finish med mild, bärliknande smak som påminner om en korsning mellan vattenmelon och bubbelgum eller kiwi.",
    badge: "Wildcard",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #0f342b, #256f4b 56%, #c8ff63)",
    image: "bilder/cactus-calamity/T/02-CactusCalamity_Front-removebg-preview.png",
    imageV1: "bilder/cactus-calamity/T/02-CactusCalamity_Front-removebg-preview.png",
    imageV2: "bilder/cactus-calamity/T/Side/03-CactusCalamity_Diago_Front-removebg-preview.png",
    flavorBadge: "Fresh / Sharp",
    flavorTag: "Cactus Lime",
    flavorNotes: "<strong>Vibe:</strong> cactus lime med frisk punch, torr heat och en look som kanns som desert-tech.",
    profile: "En med snabba flicks",
    bestFor: "Peakar alltid mid",
    packSub: "Kaktusfikon & calamansi"
  },
  {
    id: "loot-sour-shock-dose",
    slug: "loot-sour-shock-dose",
    name: "Sour Shock",
    priceSek: 289,
    stockQuantity: 0,
    note: "Sour candy / electric hit",
    description: "Sura godisar med hint av äpple. Nostalgiskt syrliga tuggummin med flytande kärna som var populära under 90- och 00-talet för den som minns.",
    badge: "Shock",
    tagTone: "",
    swatch: "linear-gradient(135deg, #19244f, #2f3ed9 45%, #63f0ff)",
    image: "bilder/loot-sour-shock-dose/T/02-loot-sour-shock-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV1: "bilder/loot-sour-shock-dose/T/02-loot-sour-shock-gamer-energy-frontal_jpg-removebg-preview.png",
    imageV2: "bilder/loot-sour-shock-dose/T/Side/03-LOOT-sour-shock-front-removebg-preview.png",
    flavorBadge: "Sour / Electric",
    flavorTag: "Shock Candy",
    flavorNotes: "<strong>Vibe:</strong> sour candy med elblatt glow, snabb attack och en hardcore arena-kansla.",
    profile: "Han, ace-jagaren",
    bestFor: "Clutch or kick",
    packSub: "Sura godisar & lite äpple"
  },
  {
    id: "loot-tiki-tropicali-dose",
    slug: "loot-tiki-tropicali-dose",
    name: "Tiki Tropicali",
    priceSek: 289,
    stockQuantity: 12,
    note: "Tropical mix / beach energy",
    description: "Tropisk sommar-tema där kokos moggar de andra smakerna av mango och ananas för en fyllig Piña colada liknande upplevelse. Naturligt mild än överdrivet söt.",
    badge: "Tropical",
    tagTone: "",
    swatch: "linear-gradient(135deg, #4f1d3c, #d55b3a 52%, #ffcf63)",
    image: "bilder/loot-tiki-tropicali-dose/T/02-loot-tiki-tropicali-gaming-booster-frontal_jpg-removebg-preview.png",
    imageV1: "bilder/loot-tiki-tropicali-dose/T/02-loot-tiki-tropicali-gaming-booster-frontal_jpg-removebg-preview.png",
    imageV2: "bilder/loot-tiki-tropicali-dose/T/Side/06-loot-tiki-tropicali-gaming-booster-profil_jpg-removebg-preview.png",
    flavorBadge: "Tropical / Warm",
    flavorTag: "Island Mix",
    flavorNotes: "<strong>Vibe:</strong> tropisk mix med varm glow, candy-fruit ton och semesterdrop fast i gamer-form.",
    profile: "TBS med 1 min max tur",
    bestFor: "Sommarlov & Garage-Lan",
    packSub: "Kokos, mango, ananas."
  },
  {
    id: "loot-kimetsu-no-kiba-dose",
    slug: "loot-kimetsu-no-kiba-dose",
    name: "Kimetsu No Kiba",
    priceSek: 289,
    stockQuantity: 0,
    note: "Limited anime / collector front",
    description: "En nostalgisk tysk \"KiBa\"-hybrid där mörka, fylliga körsbär frontar med en krämig banan-eftersmak. Upplevelsen påminner mer om en lyxig nektar eller röd godis-smoothie än en vattnig sportdryck.",
    badge: "Collab",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #123252, #1e5c4f 48%, #9ad56a)",
    image: "bilder/loot-kimetsu-no-kiba-dose/T/03-LOOT-KimetsunoKiba-Diagonal-removebg-preview.png",
    imageV1: "bilder/loot-kimetsu-no-kiba-dose/T/04-LOOT-KimetsunoKiba-Front-removebg-preview.png",
    imageV2: "bilder/loot-kimetsu-no-kiba-dose/T/Side/03-LOOT-KimetsunoKiba-Diagonal-removebg-preview.png",
    flavorBadge: "Anime / Limited",
    flavorTag: "Collector",
    flavorNotes: "<strong>Vibe:</strong> limited anime drop med collector-front, manga-energi och collab-tyngd i varje view.",
    profile: "Pay 2 win",
    bestFor: "Gacha games & Ghibli studio",
    packSub: "Körsbär & Banan-hintar."
  },
  {
    id: "loot-phoenix-flames-dose",
    slug: "loot-phoenix-flames-dose",
    name: "Phoenix Flames",
    priceSek: 289,
    stockQuantity: 6,
    note: "Fiery fruit / red-orange heat",
    description: "En explosion där den syrliga kiwin skär igenom den tunga sötman från ananasen för en riktigt \"vass\" och uppfriskande kombo. En ljus och elektrisk fruktsmak som känns betydligt uppiggande.",
    badge: "Hot Drop",
    tagTone: "",
    swatch: "linear-gradient(135deg, #48182f, #c2362f 48%, #ffb35d)",
    image: "bilder/loot-phoenix-flames-dose/T/02-LOOT-PhoenixFlames-diagonal-removebg-preview.png",
    imageV1: "bilder/loot-phoenix-flames-dose/T/03-LOOT-PhoenixFlames-front-removebg-preview.png",
    imageV2: "bilder/loot-phoenix-flames-dose/T/Side/02-LOOT-PhoenixFlames-diagonal-removebg-preview.png",
    flavorBadge: "Fiery / Loud",
    flavorTag: "Phoenix",
    flavorNotes: "<strong>Vibe:</strong> fiery fruit med varm glow, loud contrast och full phoenix-revival energi.",
    profile: "Finns bara smg & rush",
    bestFor: "Trycka en sista innan sängen",
    packSub: "Ananas & Syrlig-kiwi"
  },
  {
    id: "invincible-ice-tea",
    slug: "invincible-ice-tea",
    name: "Pixel Peach Icetea",
    priceSek: 289,
    stockQuantity: 8,
    note: "Ice tea / smooth chill",
    description: "En autentisk och krispig persika-té smak där den sträva té-basen balanserar upp den söta persikan för en läskande upplevelse. Som en iskall iste-burk direkt från kylen.",
    badge: "Smooth",
    tagTone: "alt",
    swatch: "linear-gradient(135deg, #25314c, #62748c 50%, #d7efff)",
    image: "bilder/invincible-ice-tea/T/03-PixelPeachIceTea_Front-removebg-preview.png",
    imageV1: "bilder/invincible-ice-tea/T/03-PixelPeachIceTea_Front-removebg-preview.png",
    imageV2: "bilder/invincible-ice-tea/T/Side/02-PixelPeachIceTea_FrontSideRight-removebg-preview.png",
    flavorBadge: "Iced / Smooth",
    flavorTag: "Ice Tea",
    flavorNotes: "<strong>Vibe:</strong> sval ice tea med smooth finish, clean premiumton och mindre aggressiv energikansla.",
    profile: "skärmen full av UI",
    bestFor: "Söndags-eftermiddag & öppet fönster",
    packSub: "Is-té & Persika"
  }
];

export const productMap = new Map(products.map((product) => [product.id, product]));

export function formatSek(amount) {
  return `${amount} SEK`;
}
